name: Deploy Static HTML to EC2

on:
  push:
    branches:
      - main  # Ejecuta solo en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configura AWS CLI para conectarte a la instancia EC2
    - name: Configure AWS CLI
      run: |
        sudo apt-get install -y awscli
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
        aws configure set default.region us-west-2  # Cambia según la región de tu instancia

    # 3. Copia los archivos al servidor EC2
    - name: Deploy HTML to EC2
      run: |
        scp -i /dev/null -o "StrictHostKeyChecking=no" \
          -r ./index.html ./css ./js ./img \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }}:${{ secrets.DEPLOY_PATH }}

    # 4. Reinicia Nginx en la instancia EC2
    - name: Reload Nginx
      run: |
        ssh -i /dev/null -o "StrictHostKeyChecking=no" \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} \
          "sudo systemctl reload nginx"
